# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e245e0d15abccd54fed97d803796639436793516b7e62b25ab5b081df23637db2c1052a53b50cd199978e480212838f134ccb88adfbcb920d33e172fc2a4c0eb

test:
  secret_key_base: 27444f51812d53c975928bb94247906429d8da026dcdd10fc755b7a39c0bc1504f06dae586ddd93691fe265bb8ca21d26a8ea38438329b4106f6f6103868cc2b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
